local L = select(2, ...).L('ruRU')

-- Core
L["ADDON_TITLE"] = "Телепорты в эпохальные подземелья"
L["DEFAULT_EXPANSION"] = "Дополнение по умолчанию"
L["SELECT_EXPANSION"] = "Выбрать дополнение"
L["COOLDOWN_READY"] = "Готово к использованию!"
L["COOLDOWN_NOT_READY"] = "Пока не готово!"
L["CLICK_TO_TELEPORT"] = "Нажмите, чтобы телепортироваться!"
L["TELEPORT_NOT_KNOWN"] = "Телепорт неизвестен!"
L["OPACITY_TOOLTIP"] = "Регулирует непрозрачность фона."
L["OPACITY_WARNING"] = "Изменения вступят в силу в режиме реального времени."
L["OPACITY_SLIDER"] = "Непрозрачность фона"


-- Minimap
L["NOT_INITIALIZED_MAIN"] = "DungeonTeleports: Основное окно еще не инициализировано."
L["NOT_INITIALIZED_CONFIG"] = "DungeonTeleports: Конфигурационное окно еще не инициализировано."


-- Settings
L["CONFIG_TITLE"] = "Mythic Dungeon Teleports - Настройки"
L["RESET_SETTINGS"] = "Сброс к настройкам по умолчанию"
L["RESET_TOOLTIP"] = "Сбрасывает все настройки до значений по умолчанию."
L["SHOW_MINIMAP"] = "Показать кнопку на мини-карте"
L["TOGGLE_MINIMAP"] = "Включить или выключить кнопку на мини-карте."
L["DEFAULT_EXPANSIONCONFIG"] = "Дополнение по умолчанию"
L["SELECT_EXPANSIONCONFIG"] = "Выберите дополнение, которое будет отображаться при открытии аддона."
L["DISABLE_BACKGROUND"] = "Отключить фоновые изображения"
L["DISABLE_BACKGROUND_TOOLTIP"] = "Включить или выключить фоновые изображения. Окно аддона будет закрыто для внесения изменений"


-- Expansions
L["Cataclysm"] = "Cataclysm"
L["Mists of Pandaria"] = "Mists of Pandaria"
L["Warlords of Draenor"] = "Warlords of Draenor"
L["Legion"] = "Legion"
L["Battle for Azeroth"] = "Battle for Azeroth"
L["Shadowlands"] = "Shadowlands"
L["Dragonflight"] = "Dragonflight"
L["War Within"] = "The War Within"
L["Current Season"] = "Текущий сезон"

-- Dungeons
L["DUNGEON_VORTEX_PINNACLE"] = "Вершина Смерча"
L["DUNGEON_THRONE_OF_THE_TIDES"] = "Трон Приливов"
L["DUNGEON_GRIM_BATOL"] = "Грим Батол"
L["DUNGEON_TEMPLE_OF_THE_JADE_SERPENT"] = "Храм Нефритовой Змеи"
L["DUNGEON_SIEGE_OF_NIUZAO"] = "Осада храма Нюцзао"
L["DUNGEON_SCHOLOMANCE"] = "Некроситет"
L["DUNGEON_SCARLET_MONASTERY"] = "Монастырь Алого ордена"
L["DUNGEON_SCARLET_HALLS"] = "Залы Алого ордена"
L["DUNGEON_GATE_OF_THE_SETTING_SUN"] = "Врата Заходящего Солнца"
L["DUNGEON_MOGUSHAN_PALACE"] = "Дворец Могу'шан"
L["DUNGEON_SHADO_PAN_MONASTERY"] = "Монастырь Шадо-Пан"
L["DUNGEON_STORMSTOUT_BREWERY"] = "Хмелеварня Буйных Портеров"
L["DUNGEON_SHADOWMOON_BURIAL_GROUNDS"] = "Некрополь Призрачной Луны"
L["DUNGEON_EVERBLOOM"] = "Вечное Цветение"
L["DUNGEON_BLOODMAUL_SLAG_MINES"] = "Шлаковые шахты Кровавого Молота"
L["DUNGEON_AUCHINDOUN"] = "Аукиндон"
L["DUNGEON_SKYREACH"] = "Небесный Путь"
L["DUNGEON_UPPER_BLACKROCK_SPIRE"] = "Верхняя часть пика Черной горы"
L["DUNGEON_GRIMRAIL_DEPOT"] = "Депо Мрачных Путей"
L["DUNGEON_IRON_DOCKS"] = "Железные доки"
L["DUNGEON_DARKHEART_THICKET"] = "Чаща Темного Сердца"
L["DUNGEON_BLACK_ROOK_HOLD"] = "Крепость Черной Ладьи"
L["DUNGEON_HALLS_OF_VALOR"] = "Чертоги Доблести"
L["DUNGEON_NELTHARIONS_LAIR"] = "Логово Нелтариона"
L["DUNGEON_COURT_OF_STARS"] = "Квартал Звезд"
L["DUNGEON_KARAZHAN"] = "Каражан"
L["DUNGEON_ATALDAZAR"] = "Атал'Дазар"
L["DUNGEON_FREEHOLD"] = "Вольная Гавань"
L["DUNGEON_WAYCREST_MANOR"] = "Усадьба Уэйкрестов"
L["DUNGEON_THE_UNDERROT"] = "Подгнилье"
L["DUNGEON_MECHAGON"] = "Операция Мехагон"
L["DUNGEON_SEIGE_OF_BORALUS"] = "Осада Боралуса"
L["DUNGEON_THE_NECROTIC_WAKE"] = "Смертельная тризна"
L["DUNGEON_PLAGUEFALL"] = "Чумные каскады"
L["DUNGEON_MISTS_OF_TIRNA_SCITHE"] = "Туманы Тирна Скитта"
L["DUNGEON_HALLS_OF_ATONEMENT"] = "Чертоги Покаяния"
L["DUNGEON_SPIRES_OF_ASCENSION"] = "Шпили Перерождения"
L["DUNGEON_THEATRE_OF_PAIN"] = "Театр Боли"
L["DUNGEON_DE_OTHER_SIDE"] = "Та Сторона"
L["DUNGEON_SANGUINE_DEPTHS"] = "Кровавые катакомбы"
L["DUNGEON_TAZAVESH_THE_VEILED_MARKET"] = "Тайный рынок Тазавеш"
L["DUNGEON_RUBY_LIFE_POOLS"] = "Рубиновые Омуты Жизни"
L["DUNGEON_NOKHUD_OFFENSIVE"] = "Наступление клана Нокхуд"
L["DUNGEON_AZURE_VAULT"] = "Лазурное хранилище"
L["DUNGEON_ALGETHAR_ACADEMY"] = "Академия Алгет'ар"
L["DUNGEON_ULDAMAN"] = "Ульдаман"
L["DUNGEON_NELTHARUS"] = "Нелтарий"
L["DUNGEON_BRACKENHIDE_HOLLOW"] = "Лощина Бурошкуров"
L["DUNGEON_HALLS_OF_INFUSION"] = "Чертоги Насыщения"
L["DUNGEON_DAWN_OF_THE_INFINITE"] = "Рассвет Бесконечности"
L["DUNGEON_CITY_OF_THREADS"] = "Город Нитей"
L["DUNGEON_ARA_KARA_CITY_OF_ECHOS"] = "Ара-Кара, Город Отголосков"
L["DUNGEON_STONEVAULT"] = "Каменный Свод"
L["DUNGEON_DAWNBREAKER"] = "Сияющий Рассвет"
L["DUNGEON_THE_ROOKERY"] = "Гнездовье"
L["DUNGEON_DARKFLAME_CLEFT"] = "Расселина Темного Пламени"
L["DUNGEON_CINDERBREW_BREWERY"] = "Искроварня"
L["DUNGEON_PRIORY_OF_THE_SACRED_FLAME"] = "Приорат Священного Пламени"

-- Raids
L["RAID_VAULT_OF_THE_INCARNATES"] = "Хранилище Воплощений"
L["RAID_ABBERUS_THE_SHADOWED_CRUCIBLE"] = "Аберрий, Затененное Горнило"
L["RAID_AMIRDRASSIL_THE_DREAMS_HOPE"] = "Амирдрассил, Надежда Сна"
L["RAID_CASTLE_NATHRIA"] = "Замок Нафрия"
L["RAID_SANCTUM_OF_DOMINATION"] = "Святилище Господства"
L["RAID_SEPULCHER_OF_THE_FIRST_ONES"] = "Гробница Предвечных"


